./mvnw package -Pnative -Dquarkus.native.container-runtime=docker
... works but docker hub builds fail with:

Error: Class initialization of io.netty.handler.ssl.ReferenceCountedOpenSslContext failed. Use the option --initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslContext to explicitly request delayed initialization of this class.
Original exception that caused the problem: java.lang.NoClassDefFoundError: io/netty/internal/tcnative/SSLPrivateKeyMethod

Not sure how to interpret https://quarkus.io/guides/native-and-ssl
but KKV is designed to run as sidecar without SSL