I think this reproduces the issue in #31
The test failure states plainly, without a stack trace:
org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata

Created a separate test class because interfering with the broker seemed to affect other tests